server:
  port: 9200
spring:
  #  cloud:
  #    inetutils:
  #      timeout-seconds: 10
  application:
    name: itxiaodu-credit-auth
  thymeleaf:
#    spring default route
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: xxx.xxx.xx.xxx
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
code:
  message:
    host: xxxxxxx
    path: /data/send_sms
    menthod: "POST"
    time: 3
    app-code: xxxxxxx
    sign: null
    skin: null
#mybatis:
#  mapper-locations: classpath*:mybatis/mapper/*Mapper*.xml
#logging:
#  level:
#    com.itxiaodu.credit.mapper: debug
