server:
  port: 81
spring:
  #  cloud:
  #    inetutils:
  #      timeout-seconds: 10
  application:
    name: itxiaodu-credit-zuul
  redis:
    host: xxxxx

  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    credit-portal:
      service-id: itxiaodu-credit-auth
      path: /**
    credit-project:
      service-id: itxiaodu-credit-project
      path: /project/**
    credit-order:
      service-id: itxiaodu-credit-order
      path: /order/**
    credit-pay:
      service-id: itxiaodu-credit-pay
      path: /pay/**
  host:
    connect-timeout-millis: 80000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000