server:
  port: 9800
spring:
  #  cloud:
  #    inetutils:
  #      timeout-seconds: 10
  application:
    name: itxiaodu-credit-pay
    id: itxiaodu-credit-pay
  thymeleaf:
    #    spring default route
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: xxxxx
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
alibaba:
  pay:
    app-id: xxx
    merchant-private-key:  xxxx
    alipay-public-key:  xxxx
    sign-type: RSA2
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    log-path: C:\
    main-url: http://xxx
    notify-url: /pay/notify
    return-url: /pay/return
